# File: code/settings.py
import pygame
from os.path import join
from os import walk

# General Game Settings
FPS = 60
WIDTH, HEIGHT = 1600, 900
TILE_SIZE = 64

# Player Settings
PLAYER_HEALTH = 100
PLAYER_SPEED = 400
PLAYER_ANIMATION_SPEED = 8

# Player Dash Settings
PLAYER_DASH_COOLDOWN = 2000
PLAYER_DASH_DURATION = 200
PLAYER_DASH_SPEED_MULTIPLIER = 6
PLAYER_AFTERIMAGE_ALPHA = 150
PLAYER_AFTERIMAGE_LIFETIME = 200

# Player Combat Settings
PLAYER_MAGAZINE_SIZE = 6
PLAYER_RELOAD_TIME = 1500
GAME_ATTACK_COOLDOWN = 200

# Buff settings
BUFF_DROP_CHANCE = 0.30

# Bullet Settings
BULLET_LIFETIME = 1000
BULLET_SPEED = 1500
BULLET_DAMAGE = 10

# General Enemy Settings
ENEMY_ANIMATION_SPEED = 6
ENEMY_DEATH_DURATION = 100
ENEMY_DEFAULT_VISION_RANGE = 1000
ENEMY_DEFAULT_SPEED = 250
ENEMY_DEFAULT_DISTANCE = 500

# Melee Enemy Settings
MELEE_ENEMY_HEALTH = 30
MELEE_ENEMY_SPEED = 250
MELEE_ENEMY_VISION_RANGE = 1000
MELEE_ENEMY_CONTACT_DAMAGE = 80
MELEE_ENEMY_DAMAGE_COOLDOWN = 1000

# Ranged Enemy Settings
RANGED_ENEMY_HEALTH = 20
RANGED_ENEMY_SPEED = 300
RANGED_ENEMY_VISION_RANGE = 1000
RANGED_ENEMY_SHOOT_COOLDOWN = 2000
RANGED_ENEMY_DELAY_ATTACK = 500
RANGED_ENEMY_AIMING_DURATION = 500
RANGED_ENEMY_LASER_DURATION = 200
RANGED_ENEMY_LASER_WIDTH = 100
RANGED_ENEMY_LASER_DAMAGE = 40

# Charger Enemy Settings
CHARGER_ENEMY_HEALTH = 20
CHARGER_ENEMY_VISION_RANGE = 1000
CHARGER_ENEMY_NORMAL_SPEED = 280
CHARGER_ENEMY_CHARGE_SPEED = 2800
CHARGER_ENEMY_CHARGE_COOLDOWN = 1500
CHARGER_ENEMY_CHARGE_TIME = 1000
CHARGER_ENEMY_DELAY_ATTACK = 500
CHARGER_ENEMY_CHARGE_DURATION = 800
CHARGER_ENEMY_ATTACK_RADIUS = 60
CHARGER_ENEMY_CHARGE_DAMAGE = 40

# Boss Settings
BOSS_HEALTH = 600
BOSS_SPEED = 150
BOSS_VISION_RANGE = 1000
BOSS_TIME_BETWEEN_SKILLS = 2000

# Boss Area Attack Skill
BOSS_ZONE_COUNT = 12
BOSS_ZONE_DAMAGE_PER_TICK = 30
BOSS_ZONE_TICK_INTERVAL = 1000
BOSS_ZONES_ACTIVE_DURATION = 6000
BOSS_ZONES_WARNING_DURATION = 3000
BOSS_SKILL_COOLDOWN_AFTER_ZONES = 4000

# Boss Fireball Skill
BOSS_FIREBALL_SPEED = 800
BOSS_FIREBALL_DAMAGE = 20
BOSS_FIREBALL_DELAY = 200
BOSS_FIREBALL_COUNT = 20
BOSS_FIREBALL_COOLDOWN = 4000
BOSS_FIREBALL_WARNING_DURATION = 1000
